---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
- name: instance-hplip-${MOLECULE_SCENARIO_NAME}
  image: docker.io/geerlingguy/docker-debian11-ansible:latest
  pre_build_image: true
  command: /sbin/init
provisioner:
  name: ansible
  #  config_options:
  #    ssh_connection:
  #    pipelining: true
verifier:
  name: testinfra
